### ISSUE TITLE
NPM not found @datadog/rum-react-integration

### ISSUE THREAD

**Issue by arthurhamon** [DataDog/rum-react-integration-examples#14]
Hey, I’m wondering if this project still exist ?

I read this blog post https://www.datadoghq.com/blog/datadog-rum-react-components/#add-more-context-to-user-actions

So I try to install this package and I got the npm 404 error.

`
> npm i @datadog/rum-react-integration
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@datadog%2frum-react-integration - Not found
npm ERR! 404 
npm ERR! 404  '@datadog/rum-react-integration@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`

**Comment by j-machado** [comment]
This package is not provided through NPM yet. Its main idea for now is to just serve as an example for RUM integrations.

That being said, you can still copy just what you need **or** add it to your repo with:
`yarn add https://github.com/DataDog/rum-react-integration-examples`
